themen_schlagworte = {
    "ausgeschieden": [
        ["ich", "habe", "verlassen"],
        ["postfach", "deaktiviert"],
        ["mein", "letzter", "arbeitstag"],
        ["ich", "arbeite", "nicht", "mehr"],
        ["nicht", "mehr", "im", "unternehmen"],
        ["meine", "nachfolgerin"],
        ["mein", "nachfolger"],
        ["nicht", "mehr", "tätig"],
        ["unternehmen", "verlassen"],
        ["im", "ruhestand"],
        ["nicht", "mehr", "betreut"],
        ["nicht", "mehr", "angestellt"],
        ["nicht", "mehr", "partner", "unseres", "unternehmens"],
        ["neuen", "beruflichen", "herausforderungen"],
        ["nicht", "mehr", "beschäftigt"],
        ["nicht", "mehr", "im", "dienst"],
        ["das", "haus", "verlassen"],
        ["nicht", "mehr", "ansprechpartner"],
        ["nicht", "mehr", "zu", "erreichen"],
        ["nicht", "mehr", "erreichbar"],
        ["endet", "meine", "tätigkeit"],
        ["nicht", "mehr", "über", "diese", "mail-adresse"],
        ["i", "change", "position"],
        ["has", "come", "to", "an", "end"],
        ["no", "longer", "working"],
        ["i", "have", "left"],
        ["i", "left"],
        ["i", "have", "begun", "a", "new", "role"],
        ["i", "do", "not", "work", "anymore"],
        ["no", "longer", "in", "use"],
        ["not", "anymore"],
        ["i", "have", "quit"],
        ["i", "have", "stepped", "down"],
        ["not", "longer", "active"],
        ["no", "longer", "at"],
        ["no", "longer", "available"],
        ["no", "longer", "with"],
        ["no", "longer", "be", "monitored"],
        ["no", "longer", "working"],
        ["i", "have", "now", "left"],
        ["retire"],
        ["retirement"],
        ["i'll", "be", "leaving"],
        ["no", "longer", "on", "duty"],
        ["move", "on"],
        ["moved", "on"],
        ["in", "rente"],
        ["rentenbedingt", "ausgeschieden"],
        ["pension"],
        ["nicht", "mehr", "verfügbar"],
        ["geht", "zu", "ende"],
        ["mail", "adress", "no", "longer", "valid"],
        ["ich", "verlasse"],
        ["hat", "team", "verlassen"],
        ["ich", "verlasse", "unternehmen"],
        ["entschieden", "herausforderungen"],
        ["mails", "nicht", "mehr", "gelesen"],
        ["position", "outside"],
        ["postfach", "nicht", "mehr", "aktiv"],
        ["haben", "sich", "geändert"],
        ["genieße", "den", "ruhestand"],
        ["meinen", "letzten", "arbeitstag"],
        ["letztmals", "im", "büro"],
        ["Quitté", "mes", "fonctions"],
        ["nicht", "mehr", "operativ"],
        ["account", "has", "been", "deactivated"],
        ["nicht", "mehr", "vorhanden"],
        ["scheide", "ich", "aus", "dem", "unternehmen"],
        ["nicht", "mehr", "gültig"],
        ["no", "longer", "valid"],
        ["meiner", "neuen", "mailadresse"],
        ["i", "am", "leaving"],
        ["i", "no", "longer", "work"],
        ["i", "am", "about", "to", "leave"],
        ["my", "adress", "has", "been", "migrated"],
        ["meine", "nachfolge"],
        ["insolvenz"],
        ["nicht", "mehr", "tätig"],
        ["i", "am", "no", "longer"],
        ["my", "last", "working", "day"],
        ["ende", "dienstzeit"],
        ["dienstzeit", "ende"],
        ["ich", "bin", "ausgeschieden"],
        ["hat", "kollege", "übernommen"],
        ["ich", "unternehmen", "ausgeschieden"],
        ["ik", "niet", "meer", "werkzaam"],
        ["account", "nicht", "mehr", "aktiv"],
        ["ich", "dienst", "ausgeschieden"],
        ["Nicht", "mehr", "aktiv", "ist"],
        ["Ich", "bin", "nicht", "mehr", "tätig"],
        ["nicht", "mehr", "vollumfänglich", "aktiv"],
        ["endete", "meine", "Zeit"],
        ["wird", "nicht", "mehr", "genutzt"],
        ["ich", "befinde", "mich", "nicht", "mehr", "im", "Haus"],
        ["meine", "Zuständigkeit", "hat", "sich", "geändert"],
        ["nicht", "mehr", "beim", "e.V.", "tätig"],
        ["nicht", "mehr", "für", "e.V.", "tätig"],
        ["aus", "unserem", "Unternehmen", "ausgeschieden"],
        ["Meine", "neue", "E-Mail-Adresse"],
        ["Ab", "sofort", "gibt", "es", "neue", "E-Mail-Adressen"],
        ["Meine", "E-Mail-Adresse", "hat", "sich", "geändert"],
        ["No", "longer", "aktiv"],
        ["Meine", "Anstellung", "ist", "nun", "beendet"],
        ["meinen", "Aufgabenbereich", "übernehmen"],
        ["Mailaccount", "ist", "nicht", "länger", "aktiv"],
        ["Email-Konto", "wird", "nicht", "mehr", "genutzt"],
        ["nicht", "mehr", "existent"],
        ["not", "working", "anymore"],
        ["Nicht", "mehr", "aktiv", "ist"],
        ["Ich", "bin", "nicht", "mehr", "tätig"],
        ["nicht", "mehr", "vollumfänglich", "aktiv"],
        ["endete", "meine", "Zeit"],
        ["wird", "nicht", "mehr", "genutzt"],
        ["ich", "befinde", "mich", "nicht", "mehr", "im", "Haus"],
        ["meine", "Zuständigkeit", "hat", "sich", "geändert"],
        ["nicht", "mehr", "beim", "e.V.", "tätig"],
        ["nicht", "mehr", "für", "e.V.", "tätig"],
        ["aus", "unserem", "Unternehmen", "ausgeschieden"],
        ["Meine", "neue", "E-Mail-Adresse"],
        ["Ab", "sofort", "gibt", "es", "neue", "E-Mail-Adressen"],
        ["Meine", "E-Mail-Adresse", "hat", "sich", "geändert"],
        ["No", "longer", "aktiv"],
        ["Meine", "Anstellung", "ist", "nun", "beendet"],
        ["meinen", "Aufgabenbereich", "übernehmen"],
        ["Mailaccount", "ist", "nicht", "länger", "aktiv"],
        ["Email-Konto", "wird", "nicht", "mehr", "genutzt"],
        ["nicht", "mehr", "existent"],
        ["not", "working", "anymore"],
        ["will", "be", "closed", "shortly"],
        ["will", "not", "be", "monitored"],
        ["in", "neuer", "Funktion"],
        ["I'm", "not", "using", "this", "email", "address"],
        ["No", "longer", "monitored"],
        ["I", "have", "finished", "my", "assignment"],
        ["Was", "my", "last", "day", "with"],
        ["My", "email", "address", "had", "changed", "to"],
        ["I", "have", "finished", "my", "contract", "at"],
        ["I’ve", "transitioned", "my", "email", "account"],
        ["Dieses", "Konto", "ist", "nicht", "mehr", "aktiv"],
        ["ist", "nicht", "mehr", "für", "den", "Arbeitgeberverband"],
        ["I", "have", "a", "new", "email", "address"],
        ["nicht", "mehr", "erreichen"],
        ["ihr", "neuer", "Ansprechpartner"],
        ["Postfach", "wird", "nicht", "mehr", "abgerufen"],
        ["mein", "Praktikum", "beendet"],
        ["is", "no", "longer", "Managing", "Director"],
        ["E-Mail-Postfach", "wird", "nicht", "mehr", "bedient"],
        ["Nicht", "mehr", "abgerufen", "wird"],
        ["Nicht", "länger", "in", "Betrieb"],
        ["Meinen", "Aufgabenbereich", "übernehmen"],
        ["I", "have", "moved", "to", "new", "challenges"],
        ["Eine", "neue", "Aufgabe"],
        ["Nicht", "länger", "in", "Betrieb"],
        ["Was", "my", "last", "day"],
        ["I", "will", "no", "longer", "be", "using", "this", "e-mail"],
        ["Nicht", "mehr", "aktiv"],
        ["Haben", "sich", "geändert"],
        ["Genieße", "den", "Ruhestand"],
        ["Meinen", "letzten", "Arbeitstag"],
        ["Letztmals", "im", "Büro"],
        ["Quitté", "mes", "fonctions"],
        ["Nicht", "mehr", "operativ"],
        ["Account", "has", "been", "deactivated"],
        ["No", "longer", "work"],
        ["Nicht", "mehr", "vorhanden"],
        ["Scheide", "ich", "aus", "dem", "Unternehmen"],
        ["Nicht", "mehr", "gültig"],
        ["No", "longer", "valid"],
        ["Meiner", "neuen", "Mailadresse"],
        ["I", "am", "leaving"],
        ["I", "no", "longer", "work"],
        ["I", "am", "about", "to", "leave", "my", "Adress", "has", "been", "migrated"],
        ["E-Mail", "Adress", "will", "cease", "to", "exist"],
        ["my", "last", "day", "at"],
        ["aufgrund", "meines", "Austritts"],
        ["nicht", "an", "den", "Empfänger", "zugestellt", "werden"],
        ["dieser", "email", "account", "wird", "nicht", "mehr", "benutzt"],
        ["ruhestandbedingt", "aus", "unserem", "Unternehmen", "ausgeschieden"],
        ["Diese", "E-Mail-Adresse", "ist", "INAKTIV"],
        ["Verstorben", "ist"],
        ["Die", "E-Mail-Adresse", "hat", "sich", "geändert"],
        ["Meine", "Position", "niederzulegen"],
        ["In", "den", "Ruhestand", "verabschiedet"],
        ["Ist", "nicht", "mehr", "aktiv"],
        ["My", "mandate", "came", "to", "an", "end"],
        ["I", "moved", "towards", "a", "different", "career", "path"],
        ["Nicht", "mehr", "bei", "XX", "tätig", "bin"],
        ["Already", "had", "my", "last", "day"],
        ["Die", "Adresse", "wird", "Ende", "2024", "entfernt"]
    ]
   }